### ISSUE TITLE
License of the original images that the project logo is based on / Attribution Missing

### ISSUE THREAD

**Issue by lkosmid** [federeghe/chronovise#10]
@federeghe - according to the license of each of the original images (https://creativecommons.org/licenses/by-sa/2.5/deed.en and https://support.flaticon.com/hc/en-us/articles/207248209-How-I-must-insert-the-attribution-) you need to attribute the author as well in addition to the link to the original images.

**Comment by federeghe** [comment]
Thank you, I fixed the sentence in 0e6680d and 93c8a15.
