### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by lkosmid** [federeghe/chronovise#9]
@federeghe - I tried to build the software for the JOSS review and had a problem with the compiler versions. I tried several versions of gcc up to 4.9, and clang 3.8 but they fail to compile. It builds ok with gcc-5.4. So you can modify the requirements ("What you need" Section at README.md) as follows:
A modern compiler with C++14 support like GCC (version 5 or later) or LLVM (XX version or later) and the CMake building tool.

Also for configuring the project:
In case that you have multiple complilers installed in your system, you can specify a compatible compiler as follows: 
CC=gcc-5 CXX=g++-5 cmake ..

**Comment by federeghe** [comment]
I added the requirement for GCC 5. It's strange that it does not work with clang 3.8 (it should according to their feature list). I will try in a few date and update accordingly the readme.

**Comment by federeghe** [comment]
Ok, clang 4.0 compiles the software. I changed accordingly the documentation.
